name: ped-force-net
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - torchmetrics
  - numpy
  - matplotlib
  - pandas
  - imageio
  - tqdm
  - pip
  - pip:
      - opencv-python
