model_type: direct_net
batch_size: 64
epochs: 4
learning_rate: 1e-3
hidden_dims: [512, 512, 256]
pred_steps: 8
dropout: 0.0

dataset: julich
data_folder_path: "./data/datasets/julich_bottleneck_caserne"
# train_scenes: [b090, b100, b110, b120, b140, b160, b180, b200, b220, l0, l2, l4]
train_scenes: [b090]
val_scenes: [b250]
fdm_window_size: 20
sampling_step: 1