model_type: neural_net
batch_size: 64
epochs: 3
learning_rate: 1e-3
hidden_dim: 256
val_ratio: 0.1

dataset_path: "./data/preprocessed/juelich_bneck_labeled_sstep1.ndjson"
dataset_format: "ndjson"
n_samples: 150000