batch_size: 512
epochs: 2
learning_rate: 1e-3
interaction_size: 512
hidden_sizes: [1024]
val_ratio: 0.2

datasets:
  # trajnet++/train/real_data
  - name: "biwi_hotel"
    path: "./data/datasets/trajnet++/train/real_data/biwi_hotel.ndjson"
    type: "trajnet++"
  # - name: "cff_06"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_06.ndjson"
  #   type: "trajnet++"
  # - name: "cff_07"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_07.ndjson"
  #   type: "trajnet++"
  # - name: "cff_08"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_08.ndjson"
  #   type: "trajnet++"
  # - name: "cff_09"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_09.ndjson"
  #   type: "trajnet++"
  # - name: "cff_10"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_10.ndjson"
  #   type: "trajnet++"
  # - name: "cff_12"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_12.ndjson"
  #   type: "trajnet++"
  # - name: "cff_13"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_13.ndjson"
  #   type: "trajnet++"
  # - name: "cff_14"
  #   path: "./data/datasets/trajnet++/train/real_data/cff_14.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_students001"
  #   path: "./data/datasets/trajnet++/train/real_data/crowds_students001.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_students003"
  #   path: "./data/datasets/trajnet++/train/real_data/crowds_students003.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_zara01"
  #   path: "./data/datasets/trajnet++/train/real_data/crowds_zara01.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_zara03"
  #   path: "./data/datasets/trajnet++/train/real_data/crowds_zara03.ndjson"
  #   type: "trajnet++"
  # - name: "lcas"
  #   path: "./data/datasets/trajnet++/train/real_data/lcas.ndjson"
  #   type: "trajnet++"
  # - name: "wildtrack"
  #   path: "./data/datasets/trajnet++/train/real_data/wildtrack.ndjson"
  #   type: "trajnet++"
  # trajnet++/train/synth_data
  - name: "orca_synth"
    path: "./data/datasets/trajnet++/train/synth_data/orca_synth.ndjson"
    type: "trajnet++"