save_format: "json"  # or "pickle"
output_path: "./data/preprocessed"

datasets:
  - juelich_bneck:
      compute_fdm: true
      input_folder: "./data/datasets/juelich/bottleneck/"
      sampling_step: 10
      fdm_settings:
        fdm_window_size: 20
      names:
        - "b090"
        - "b100"
        - "b120"
        - "b120"
        - "b140"
        - "b160"
        - "b180"
        - "b200"
        - "b220"
        - "b250"
        - "l0"
        - "l2"
        - "l4"
  # trajnet++/train/real_data
  # - name: "biwi_hotel"
  #   input_path: "./data/datasets/trajnet++/train/real_data/biwi_hotel.ndjson"
  #   type: "trajnet++"
  # - name: "cff_06"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_06.ndjson"
  #   type: "trajnet++"
  # - name: "cff_07"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_07.ndjson"
  #   type: "trajnet++"
  # - name: "cff_08"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_08.ndjson"
  #   type: "trajnet++"
  # - name: "cff_09"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_09.ndjson"
  #   type: "trajnet++"
  # - name: "cff_10"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_10.ndjson"
  #   type: "trajnet++"
  # - name: "cff_12"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_12.ndjson"
  #   type: "trajnet++"
  # - name: "cff_13"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_13.ndjson"
  #   type: "trajnet++"
  # - name: "cff_14"
  #   input_path: "./data/datasets/trajnet++/train/real_data/cff_14.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_students001"
  #   input_path: "./data/datasets/trajnet++/train/real_data/crowds_students001.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_students003"
  #   input_path: "./data/datasets/trajnet++/train/real_data/crowds_students003.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_zara01"
  #   input_path: "./data/datasets/trajnet++/train/real_data/crowds_zara01.ndjson"
  #   type: "trajnet++"
  # - name: "crowds_zara03"
  #   input_path: "./data/datasets/trajnet++/train/real_data/crowds_zara03.ndjson"
  #   type: "trajnet++"
  # - name: "lcas"
  #   input_path: "./data/datasets/trajnet++/train/real_data/lcas.ndjson"
  #   type: "trajnet++"
  # - name: "wildtrack"
  #   input_path: "./data/datasets/trajnet++/train/real_data/wildtrack.ndjson"
  #   type: "trajnet++"
  # trajnet++/train/synth_data
  # - name: "orca_synth"
  #   input_path: "./data/datasets/trajnet++/train/synth_data/orca_synth.ndjson"
  #   type: "trajnet++"