model_type: social_force
batch_size: 64
epochs: 3
learning_rate: 1e-2
pred_steps: 10

weights:
  keras_random: True
  params:
    A_interaction: 3.5
    B_interaction: 0.6
    A_obstacle: 5.0
    B_obstacle: 0.2
    tau: 0.5
    desired_speed: 0.7

dataset: juelich
data_folder_path: "./data/datasets/juelich/bottleneck"
# train_scenes: [b090, b100, b110, b120, b140, b160, b180, b200, b220, l0, l2, l4]
train_scenes: [b090]
val_scenes: [b250]
fdm_window_size: 20
sampling_step: 1